Csc bdse task3
slvlyc1/csc-bdse pull request #4
Opened 2018-04-06 17:47 UTC by butnotstupid

2018-04-09 10:41 UTC, dormidon commented on README.md
> + * интеграционные тесты
А предполагаются быть реализованными?

2018-04-09 10:44 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/controller/CoordinatorController.java
> +public class CoordinatorController {
А стандартный контроллер (для интерфейса `KeyValueApi`) здесь почему не подходит?

2018-04-09 10:47 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +        List<Thread> putThreads = keyValueNodes.stream().map(node -> new Thread(() -> {
Использование API потоков в таких задачах - антипаттерн. Поток - довольно тяжелая сущность, которая создается и уничтожается не быстро, происходит много взаимодействия с операционной системой.
Гораздо лучше использовать `ExecutorService` - этот инструмент как раз позволяет писать код, разделяя описание задачи от ее исполнения, а так же контролируя параллелизм и concurrency.

2018-04-09 10:49 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +        if (nodeStatus.equals(DOWN)) throw new IllegalStateException(String.format("Node '%s' is down", nodeName));
Проверка повторяется в каждо методе.
Можно вынести в метод `requireUpNode`.

2018-04-09 10:51 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +        List<Thread> getThreads = keyValueNodes.stream().map(node -> new Thread(() ->
Паттерн "выполнить какое-то количество задач параллельно, потом дождаться определенного числа результатов" повторяется из метода в метод. 
Нельзя ли это абстрагировать?

2018-04-09 10:51 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +            RecordWithTimestamp resolvedRecord = new LatestValueConflictResolver().resolve(conflictingRecords);
Обязательно ли каждый раз создавать экземпляр `LatestValueConflictResolver-а`?

2018-04-09 10:54 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +        return keyValueNodes;
Возвращаем наружу исходный список. Кто-то может его модифицировать невзначай.
Самый правильный вариант будет скопировать в конструкторе исходный список в immutable-обертку (`Collections.immutableList`) и его использовать. Тогда возвращать наружу его будет безопасно.

2018-04-09 10:58 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApiHttpClient.java
> +public class CoordinatorKeyValueApiHttpClient implements KeyValueApi {
А почему клиент к обычному `KeyValueApi` не подходит?

2018-04-09 11:02 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/LatestValueConflictResolver.java
> +                // taking the most common value
А для чего мы берем самое общее?
Логика `LastWriteWins` заключается в том, что нужно брать самое свежее значение, независимо от того, как часто оно встречается.

2018-04-09 11:03 UTC, dormidon commented on bdse-kvnode/src/test/java/ru/csc/bdse/kv/LatestValueConflictResolverTest.java
> +        RecordWithTimestamp recordOne = new RecordWithTimestamp("valueOne".getBytes(), 123000, false, "NODE_ONE");
Можно сделать у `RecordWithTimestamp` конструктор, который принимает строку. Клиентский код, типа этого, будет лаконичней.

2018-04-09 11:04 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/LatestValueConflictResolver.java
> +                // taking the most common value
Туплю, это для случая, если времена все совпадают.

2018-04-09 11:07 UTC, dormidon commented on bdse-kvnode/src/test/java/ru/csc/bdse/kv/LatestValueConflictResolverTest.java
> +    public void resolveMostCommonValue() throws Exception {
Было бы круто добавить еще тест, где у большинства записей совпадает время и значение, но есть одна свежее с другим значением. 
Это поможет убедиться, что наш резовлер имеет приоритет по свежести перед "общностью" значений.

2018-04-09 11:09 UTC, dormidon requested changes
В целом - все хорошо. Алгоритм резолвинга реализовали и протестировали. Будет круто, если доделаем:
  1. Уберем дублирование кода координаторе
  2. Уберем лишние контроллеры и клиенты к координатору (их можно заменить на контроллер и клиент к обычному `KeyValueApi`
  3. Попробуем координатора "в деле" - в интеграционных тестах.

2018-04-13 06:18 UTC, butnotstupid commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApiHttpClient.java
> +public class CoordinatorKeyValueApiHttpClient implements KeyValueApi {
этот клиент имеет список url-ов координаторов и реализует логику retry:

> - создать расширение `KeyValueApiHttpClient` для работы со списком нод-координаторов. Клиент работает со списком 
равнозначных нод-координаторов, если происходит ошибка связи с координатором 1, то перация исполняется на 
координаторе 2 и далее

2018-04-13 06:20 UTC, butnotstupid commented on bdse-kvnode/src/main/java/ru/csc/bdse/controller/CoordinatorController.java
> +public class CoordinatorController {
переделал

теперь есть абстрактный и два расширения, где я указываю, какой бин KeyValueApi брать для конструктора

2018-04-13 06:21 UTC, butnotstupid commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +        if (nodeStatus.equals(DOWN)) throw new IllegalStateException(String.format("Node '%s' is down", nodeName));
выделил requireUpNode

2018-04-13 06:22 UTC, butnotstupid commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +            RecordWithTimestamp resolvedRecord = new LatestValueConflictResolver().resolve(conflictingRecords);
да, каждый раз не обязательно. теперь создаю один на координатор.

2018-04-13 06:23 UTC, butnotstupid commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +        return keyValueNodes;
спасибо, отличное замечание, поправил.

2018-04-13 06:23 UTC, butnotstupid commented on bdse-kvnode/src/test/java/ru/csc/bdse/kv/LatestValueConflictResolverTest.java
> +        RecordWithTimestamp recordOne = new RecordWithTimestamp("valueOne".getBytes(), 123000, false, "NODE_ONE");
да, добавил, в тесте теперь стало покрасивее

2018-04-13 06:24 UTC, butnotstupid commented on bdse-kvnode/src/test/java/ru/csc/bdse/kv/LatestValueConflictResolverTest.java
> +    public void resolveMostCommonValue() throws Exception {
да, добавил `resolveLatestRareValue()` тест

2018-04-13 06:28 UTC, butnotstupid commented
Поправил большую часть комментов. 

Точно доделаю ExecutorService и выделение отдельного метода "выполнить параллельно, собрать количество результатов до таймаута". Интеграционный тест -- вероятность остается, но она невелика.

2018-04-13 10:12 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/controller/OneNodeKeyValueApiController.java
> +public class OneNodeKeyValueApiController extends AbstractKeyValueApiController{
Это прекрасно :)
Код, отличающийся только аннотациями :)

2018-04-13 10:14 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApi.java
> +        this.keyValueNodes = Collections.unmodifiableList(keyValueNodes);
На самом деле, тут еще остается возможность модификации, если у кого-то останется ссылка на исходный `keyValueNodes`. 
Чтобы было совсем безопасно - надо честно создать новый список с тем же содержимым, и его уже обернуть в неизменяемую коллекцию.

2018-04-13 10:35 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/CoordinatorKeyValueApiHttpClient.java
> +public class CoordinatorKeyValueApiHttpClient implements KeyValueApi {
Понял.

2018-04-13 10:36 UTC, dormidon commented on bdse-kvnode/src/test/java/ru/csc/bdse/kv/LatestValueConflictResolverTest.java
> +    public void resolveMostCommonValue() throws Exception {
Ок.

2018-04-17 10:36 UTC, dormidon approved these changes
Ставим 4, ибо нет интеграционных тестов и не убрано дублирование кода.

2018-05-01 20:29 UTC, merged